### ISSUE TITLE
全屏显示

### ISSUE THREAD

**Issue by Crowds21** [VIWZ/Room#1]
刚好也在做透明的主题,也遇见了这个问题,全屏模式这样设置效果会好一点,这样就不需要隐藏设置栏目了.
开启全屏的时候,主体显示部分会多一个类.protyle--fullscreen ,给该类加一个背景,然后.protyle-content是遮罩在他的上面的,加一个选择器就好.
```css
/*全屏模式下会出现该类*/
.protyle--fullscreen{
	background-image:var(--allen-background-image)!important;
	background-position:center;
	background-size:cover;
	background-repeat:no-repeat;    
}
/**一个选择器,全屏模式下才会触发**/
.protyle--fullscreen .protyle-content{
    backdrop-filter: blur(30px);
	background-color:#2b2b2bAA!important;
}
```
